### ISSUE TITLE
[bug] Infinite scroll on "new OBJKTs" feed is broken

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#110]
basically what it says in the headline: 
The infinite scroll of the "new OBJKTs" feed doesnt work, stopy after 8 or so objkts

**Comment by melMass** [comment]
Not really after 8 but it's indeed stopping after ~30-40.
I still haven't looked into it but it should be fairly obvious to spot with a debugger

**Comment by Zir0h** [comment]
I think it stops when you encounter a large amount of restricted objects, but I haven't been able to look further.

**Comment by melMass** [comment]
> I think it stops when you encounter a large amount of restricted objects, but I haven't been able too look further.

Interesting thanks! I will look at it tonight with that in mind

**Comment by xat** [comment]
i can also have a look at this as part of the refactoring branch. there i changed the feed logic quite a bit.

**Comment by melMass** [comment]
@xat Did you nailed the issue in the refacto? Should I maybe look into fixing it sooner than the PR merge?

**Comment by xat** [comment]
yeah, it's fixed in the refactoring branch, but that might indeed still take a bit of time until it's ready to be merged.

**Comment by melMass** [comment]
@xat @jagracar ... I just have a doubt, I can't see the error anymore, can you confirm? was it just not deployed when this issue was filed?

**Comment by jagracar** [comment]
It's something that doesn't happen always. It might be connected with some special tokens. That's what makes this issue tricky. It happened again one week ago and since then it didn't happen again, but i would be surprised if it's solved.

**Comment by jagracar** [comment]
I will try to let you know when I see it.

**Comment by jagracar** [comment]
Happening now @melMass 
The last visible OBJKT is 763828

**Comment by melMass** [comment]
> It might be connected with some special tokens.

That's my guess too!
I'll try to pinpoint it!

**Comment by Zir0h** [comment]
It happens on recent sales too, stuck at 680282.

Probably because an objkt was very popular recently:
![image](https://user-images.githubusercontent.com/546070/182033609-141bedc7-2a06-4b0b-94fe-7e435dfedbe9.png)
748249 in this case

//edit: this looks indeed like it's fixed in #80 so nevermind! :sweat_smile: 

#80 seems stuck on 762761 for new objkt feed

**Comment by melMass** [comment]
Interesting, it's still stuck on 762761 an hour later

**Comment by jagracar** [comment]
I think it remains always stuck. At some moment is so old that you don't notice anymore, because you need to scroll down a lot

**Comment by melMass** [comment]
Trying to comeup with an automated way to test this in #144

**Comment by Zir0h** [comment]
tz1QY9YLf2QmVuF4xukH56NMjqdgK6T7EA6x created a lot of new objkts in a short amount of time. Only the last one is shown on the frontend, even though there are many more returned by the indexer:
![image](https://user-images.githubusercontent.com/546070/184586222-7d08a12e-aed5-4a2e-b9cb-5fb6a7d5aee1.png)

id's 768236 - 768280 are from the same account

Maybe because of this [uniq](https://github.com/teia-community/teia-ui/blob/52ce00c7ad72e6e8850d49797213540de352dd18/src/pages/feeds/feeds.js#L205) ?

**Comment by jagracar** [comment]
I think that's another thing. If i remember well, there is some kind of filter to avoid that a single user blocks the complete scroll by minting too many OBJKTs at the same time

**Comment by melMass** [comment]
This was autoclosed by reference... re-opening and re-investigating ;)
