### ISSUE TITLE
[bug] interactive OBJKTs are not vertically aligned when using fullscreen mode on the minting preview page

### ISSUE THREAD

**Issue by SableRaf** [teia-community/teia-ui#39]
**Describe the bug**
Interactive OBJKTs are not vertically aligned when using fullscreen mode on the minting preview page. The vertical alignment is correct in fullscreen mode once the OBJKT is minted.

**To Reproduce**
1. go to mint page
2. upload an interactive OBJKT
3. go to preview page
4. open full screen mode (the issue is more obvious on larger monitors)

**Expected behavior**
The OBJKT should appear vertically centered

**Screenshots**
![image](https://user-images.githubusercontent.com/290261/159752769-53ff21d9-2b87-4ec5-9063-eabb5ed75f66.png)
Preview

![image](https://user-images.githubusercontent.com/290261/159752791-1b12b091-cc90-4c64-be97-fcb15ec45b56.png)
Minted

---

### Tasks:

- [x] Fix the preview page for interactive tokens in fullscreen.
- [ ] Vertically center non full width/height tokens:
    As mentioned by formless on discord
    ![image](https://user-images.githubusercontent.com/7041726/162426830-b91df1ca-bc46-466c-b253-7819b36a17cf.png)
    https://teia.art/objkt/670193 - Shifted
    https://versum.xyz/token/versum/18814 - Working

**Comment by melMass** [comment]
@kylegrover If you are interested to look into this with me! 
It relies on the strange gh-page setup that I yet have to decipher! I think you might know more about it.

**Comment by melMass** [comment]
Hello @SableRaf ,

The preview for interactive tokens is fixed in #146 and it will close this issue as after debugging formless's token I realise this is because they did not follow the guide on styling. 
If you inspect the token once in fullscreen you'll understand what I mean.

For unity I made a template specifically for that: https://github.com/melMass/hen.unity-webgl-template

That you can preview here: https://teia.art/objkt/603254 (slow to load unfortunately)
