### ISSUE TITLE
[support] What's the use of the "Transfer" tab on OBJKTs in my wallet?

### ISSUE THREAD

**Issue by 852Kerfunkle** [teia-community/teia-ui#42]
I've come across it today and though how convenient. It doesn't appear to be for FA2 transfers?

Thanks!

**Comment by xat** [comment]
maybe the goal of this issue could be that we add a small help text?

**Comment by merchantcoppola** [comment]
as far as i know the "transfer" is meant to only be used for transferring OBJKTs from a collab contract to a tez address, because you cant access/tranfer these tokens from your wallet.

suggestion

**either a more clear text**, like changing the text when not available from
"You do not have any editions available to transfer."
to
"This Transfer function can be used for transfering tokens from a **collaboration contract** you are logged into. You do not have any editions available to transfer this way. "

or **hiding the "transfer" tab** when not logged into a collab contract if possible

**Comment by melMass** [comment]
Just tidying up. 
Merchant PRed the warning text change.
If needed re-create an issue to add 'Transfer' for non collab tokens
